# Generated by Django 5.0 on 2024-01-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quontity',
            new_name='quantity',
        ),
    ]
