# Generated by Django 5.0 on 2024-01-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_quontity_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
    ]
