# Generated by Django 5.0.1 on 2024-01-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilepic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
