# Generated by Django 5.0.1 on 2024-01-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profilepic',
            new_name='image',
        ),
    ]
